### ISSUE TITLE
Proposal: Add concept of "events" to pipeline execution criteria

### ISSUE THREAD

**Issue by krancour** [lovethedrake/drakecore#2]
Moved over from https://github.com/lovethedrake/prototype/issues/28

## Status Quo

Currently, the method of describing criteria for pipeline execution is a little bit clunky.

Take this, for example:

```
pipelines:
  test:
    criteria:
      branches:
        ignore:
        - master
```

What this says is that this pipeline should execute any time the "branch" isn't master, but it isn't very clear in communicating my actual intent and may select some conditions I didn't intend. My intent, in this case, was to execute for all all pull requests. This works, because in the event of a pull request, the custom Brigade worker (the only implementation that these pipeline execution criteria _currently_ applies to) considers the source branch to be the empty string and "" != "master". But there are two problems here:

1. I needed to know something esoteric about the worker's behavior-- namely that it considers the source branch of pull requests to be the empty string. It wouldn't have been outrageous, for instance, to assume that the worker would consider the target branch of a pull request as the "branch" in question, in which case, one would look at these criteria and wonder why this pipelines does execute for pull requests.

1. This will also execute on pushes to any branch that isn't master. That may not be a bad thing if that is what you want, but in this case, it isn't actually what I wanted.

1. Other implementations with their own idiosyncrasies will come along. If we want pipelines to be portable, the meaning of any given pipeline definition cannot be subject to underlying implementation details.

A second example:

```
pipelines:
  master:
    criteria:
      branches:
        only:
        - master
```

Here, the master pipeline runs for pushes to the master branch. But it doesn't run when a new tag is applied to the master branch. This was my intended behavior, but why does it work this way? Because if the Brigade worker has a ref / tag, it only considers that tag in selecting pipelines for execution. The branch doesn't factor into the selection process at all. Again-- this is some esoteric system behavior one needs to be aware of to be successful.

## Proposal

If we introduce the concept of events, we can be unambiguous about the criteria for pipeline execution.

For example:

```
pipelines:
  test:
    criteria:
      events:
        git:
          pullRequest:
            targetBranches:
              only:
              - master
              - /feature\/.*/
```

This unambiguously says it should execute when triggered by pull requests targeted at the master branch or any feature branch.

```
pipelines:
  master-or-feature:
    criteria:
      events:
        git:
          push:
            branches:
              only:
              - master
              - /feature\/.*/
```

This unambiguously says it should execute when triggered by pushes to the master branch or any feature branch.

```
pipelines:
  release:
    criteria:
      events:
        git:
          tag:
            only:
            - /v[0-9]+(\.[0-9]+)*(\-.+)?/
```

This unambiguously says it should execute when triggered by the application of a new semver tag.

In all three of the updated examples, there is no question about the circumstances under which each pipeline is executed.

Note also that all events described above are git-specific. Git it ubiquitous enough that it makes sense to build support for git-based events into the core spec, but we should also recognize the opportunity to allow some extension points here so that pipelines can be triggered by events from other integrations. (We _might_ even discover that the example above are more Github-specifc than they are git-specific. For instance, I believe that Gitlab uses different parlance for what Github calls a "pull request." We can cross this bridge if/when we come to it-- but before any spec is GA.)
